### ISSUE TITLE
Implement a class to crop video according to time frames and convert them to sinple video file.

### ISSUE THREAD

**Issue by DeboDevelop** [IOStream-OpenEnd/MagikMoments#15]
Here's the plan, we will create 2 arrays. One to save the time stamps. Then we will cut the video from 2 sec before the time stamp and 2 sec after the time stamp. Then we we will combine it in one video file and output it.

**Comment by masterchef2209** [comment]
i would like to work on this.

**Comment by DeboDevelop** [comment]
Thanks.
