### ISSUE TITLE
Detect Face from the video frames and convert it into grayscale.

### ISSUE THREAD

**Issue by DeboDevelop** [IOStream-OpenEnd/MagikMoments#6]
Have to find a python Library to detect emotions using machine learning and image processing.

**Comment by Pawank221** [comment]
check out this , https://www.apprendimentoautomatico.it/apprendimentoautomatico-wpblog/en/emotions-detection-via-facial-expressions-with-python-opencv/

**Comment by shubham-chhimpa** [comment]
https://github.com/MauryaRitesh/Facial-Expression-Detection/blob/master/README.md
